#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <target file or dir>"
  exit 1
fi

target="$1"
target="$(readlink -e "$target")"

if [ -z "$target" ]; then
  echo "$1: must be existing file or path."
  exit 1
fi

xhost +

docker \
  run \
  -it \
  --rm \
  --dns=8.8.8.8 \
  -e DISPLAY="$DISPLAY" \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.WebIde100:/root/.WebIde100 \
  -v "$target":/root/target \
  phpstorm "/root/target"
